import clsx from 'clsx'
import { Lexend_Deca } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import 'react-lite-youtube-embed/dist/LiteYouTubeEmbed.css'

import AppContext from '@/context/AppContext'

import { ThemeInit } from '../.flowbite-react/init'
import './globals.css'
import 'react-lite-youtube-embed/dist/LiteYouTubeEmbed.css'
import { NextIntlClientProvider } from 'next-intl'
import clsx from 'clsx'
import AppContext from '@/context/AppContext'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/authOptions'
import SessionProvider from '@/context/SessionProvider'

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: ['200', '500'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang='pl' className={clsx(lexendDeca.className, 'h-full')}>
      <body className='h-full min-h-screen'>
        <ThemeInit />
        <SessionProvider session={session}>
          <AppContext>
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
          </AppContext>
        </SessionProvider>
      </body>
    </html>
  )
}
