import { Lexend_Deca } from 'next/font/google'
import { ThemeInit } from '../.flowbite-react/init'
import './globals.css'
import 'react-lite-youtube-embed/dist/LiteYouTubeEmbed.css'
import { NextIntlClientProvider } from 'next-intl'
import clsx from 'clsx'

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: ['200', '500'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='pl' className={clsx(lexendDeca.className, 'h-full')}>
      <body className='h-full min-h-screen'>
        <ThemeInit />
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  )
}
